name: Candidate CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  use-template:
    uses: talentis-io/ci-cd-template/.github/workflows/react-run.yml@main
    with:
      repo_name: ${{ github.event.repository.name }}
    secrets: inherit
